spring:
  application:
    name: travel-strategy
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/wolf2w-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
  rabbitmq:
    addresses: 192.168.171.134:5672
    username: root
    password: root
    virtual-host: /
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8097
feign:
  client:
    config:
      default:
        loggerLevel: FULL
